# Generated by Django 5.0.4 on 2026-02-27 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('min_score', models.PositiveIntegerField()),
                ('max_dti', models.DecimalField(decimal_places=2, max_digits=5)),
                ('min_income', models.DecimalField(decimal_places=2, max_digits=14)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='banks.bank')),
            ],
        ),
    ]
