# Generated by Django 5.0.4 on 2026-02-28 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_bankproduct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking_version', models.CharField(max_length=20)),
                ('user_score', models.IntegerField()),
                ('approval_probability', models.DecimalField(decimal_places=4, max_digits=6)),
                ('dti_ratio', models.DecimalField(decimal_places=4, max_digits=6)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=14)),
                ('risk_category', models.CharField(max_length=20)),
                ('min_market_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_market_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('feature_vector', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
