# Generated by Django 5.0.4 on 2026-02-28 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0003_recommendationsnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked', models.BooleanField(default=False)),
                ('applied', models.BooleanField(default=False)),
                ('approved', models.BooleanField(blank=True, null=True)),
                ('ranking_version', models.CharField(max_length=20)),
                ('ranking_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='bankproduct',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='bank',
            index=models.Index(fields=['is_active'], name='banks_bank_is_acti_aa8e36_idx'),
        ),
        migrations.AddIndex(
            model_name='bank',
            index=models.Index(fields=['priority_weight'], name='banks_bank_priorit_2b3870_idx'),
        ),
        migrations.AddIndex(
            model_name='bankproduct',
            index=models.Index(fields=['is_active'], name='banks_bankp_is_acti_7fcd0d_idx'),
        ),
        migrations.AddIndex(
            model_name='bankproduct',
            index=models.Index(fields=['min_score'], name='banks_bankp_min_sco_d5b9bf_idx'),
        ),
        migrations.AddIndex(
            model_name='bankproduct',
            index=models.Index(fields=['interest_rate'], name='banks_bankp_interes_aaef62_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationsnapshot',
            index=models.Index(fields=['user'], name='banks_recom_user_id_58d044_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationsnapshot',
            index=models.Index(fields=['ranking_version'], name='banks_recom_ranking_1c6890_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationsnapshot',
            index=models.Index(fields=['created_at'], name='banks_recom_created_7fcedf_idx'),
        ),
        migrations.AddField(
            model_name='recommendationinteraction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='banks.bankproduct'),
        ),
        migrations.AddField(
            model_name='recommendationinteraction',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='banks.recommendationsnapshot'),
        ),
        migrations.AddField(
            model_name='recommendationinteraction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='recommendationinteraction',
            index=models.Index(fields=['user'], name='banks_recom_user_id_253b91_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationinteraction',
            index=models.Index(fields=['product'], name='banks_recom_product_7e3c29_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationinteraction',
            index=models.Index(fields=['ranking_version'], name='banks_recom_ranking_82b88d_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationinteraction',
            index=models.Index(fields=['created_at'], name='banks_recom_created_a03502_idx'),
        ),
    ]
