# Generated by Django 5.0.4 on 2026-03-11 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0004_recommendationinteraction_alter_bankproduct_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='banks.bank')),
            ],
            options={
                'ordering': ['bank', 'name'],
                'indexes': [models.Index(fields=['bank'], name='banks_bankb_bank_id_706928_idx'), models.Index(fields=['is_active'], name='banks_bankb_is_acti_336646_idx')],
            },
        ),
    ]
