# Generated by Django 5.0.4 on 2026-03-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0005_bankbranch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='bank',
            name='priority_weight',
            field=models.IntegerField(db_index=True, default=50),
        ),
        migrations.AlterField(
            model_name='bankbranch',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='bankbranch',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='bankbranch',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='bankproduct',
            name='interest_rate',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='bankproduct',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='bankproduct',
            name='min_score',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='recommendationinteraction',
            name='ranking_version',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='recommendationsnapshot',
            name='ranking_version',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
