# Generated by Django 5.0.4 on 2026-03-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0006_alter_bank_is_active_alter_bank_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankbranch',
            name='city',
            field=models.CharField(default='Tashkent', max_length=100),
        ),
        migrations.AddField(
            model_name='bankbranch',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bankbranch',
            name='working_hours',
            field=models.CharField(default='09:00 - 18:00', max_length=100),
        ),
    ]
