# Generated by Django 5.0.4 on 2026-03-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0008_bankproduct_description_bankproduct_source_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankproduct',
            options={'ordering': ['-is_featured', 'interest_rate']},
        ),
        migrations.AddField(
            model_name='bank',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='currency',
            field=models.CharField(choices=[('UZS', 'UZS'), ('USD', 'USD')], default='UZS', max_length=10),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='product_type',
            field=models.CharField(choices=[('loan', 'Loan'), ('credit_card', 'Credit Card'), ('deposit', 'Deposit'), ('mortgage', 'Mortgage')], db_index=True, default='loan', max_length=20),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='priority_weight',
            field=models.FloatField(db_index=True, default=1.0),
        ),
        migrations.AddIndex(
            model_name='bank',
            index=models.Index(fields=['slug'], name='banks_bank_slug_86c22c_idx'),
        ),
        migrations.AddIndex(
            model_name='bankproduct',
            index=models.Index(fields=['product_type'], name='banks_bankp_product_2fdd24_idx'),
        ),
    ]
