# Generated by Django 5.0.4 on 2026-04-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0009_alter_bankproduct_options_bank_logo_bank_slug_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bank',
            name='banks_bank_is_acti_aa8e36_idx',
        ),
        migrations.RemoveIndex(
            model_name='bank',
            name='banks_bank_priorit_2b3870_idx',
        ),
        migrations.RemoveIndex(
            model_name='bank',
            name='banks_bank_slug_86c22c_idx',
        ),
        migrations.RemoveIndex(
            model_name='bankbranch',
            name='banks_bankb_bank_id_706928_idx',
        ),
        migrations.RemoveIndex(
            model_name='bankbranch',
            name='banks_bankb_is_acti_336646_idx',
        ),
        migrations.RemoveIndex(
            model_name='bankproduct',
            name='banks_bankp_is_acti_7fcd0d_idx',
        ),
        migrations.RemoveIndex(
            model_name='bankproduct',
            name='banks_bankp_min_sco_d5b9bf_idx',
        ),
        migrations.RemoveIndex(
            model_name='bankproduct',
            name='banks_bankp_interes_aaef62_idx',
        ),
        migrations.RemoveIndex(
            model_name='bankproduct',
            name='banks_bankp_product_2fdd24_idx',
        ),
        migrations.RemoveIndex(
            model_name='recommendationinteraction',
            name='banks_recom_user_id_253b91_idx',
        ),
        migrations.RemoveIndex(
            model_name='recommendationinteraction',
            name='banks_recom_product_7e3c29_idx',
        ),
        migrations.RemoveIndex(
            model_name='recommendationinteraction',
            name='banks_recom_ranking_82b88d_idx',
        ),
        migrations.RemoveIndex(
            model_name='recommendationinteraction',
            name='banks_recom_created_a03502_idx',
        ),
        migrations.RemoveIndex(
            model_name='recommendationsnapshot',
            name='banks_recom_user_id_58d044_idx',
        ),
        migrations.RemoveIndex(
            model_name='recommendationsnapshot',
            name='banks_recom_ranking_1c6890_idx',
        ),
        migrations.RemoveIndex(
            model_name='recommendationsnapshot',
            name='banks_recom_created_7fcedf_idx',
        ),
        migrations.AddField(
            model_name='bank',
            name='normalized_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='normalized_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='bankproduct',
            unique_together={('bank', 'normalized_name')},
        ),
    ]
