# Generated by Django 5.0.4 on 2026-04-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0010_remove_bank_banks_bank_is_acti_aa8e36_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankproduct',
            name='has_rate',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='source',
            field=models.CharField(db_index=True, default='bank.uz', max_length=50),
        ),
        migrations.AlterField(
            model_name='bank',
            name='normalized_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bankproduct',
            name='normalized_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bankproduct',
            name='product_type',
            field=models.CharField(choices=[('loan', 'Loan'), ('micro', 'Microloan'), ('auto', 'Auto Loan'), ('mortgage', 'Mortgage'), ('online', 'Online Loan'), ('credit_card', 'Credit Card'), ('deposit', 'Deposit')], db_index=True, default='loan', max_length=20),
        ),
    ]
