# Generated by Django 5.0.4 on 2026-04-10 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0011_bankproduct_has_rate_bankproduct_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bankproduct',
            unique_together={('bank', 'source_url')},
        ),
        migrations.AlterField(
            model_name='recommendationinteraction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks.bankproduct'),
        ),
        migrations.AlterField(
            model_name='recommendationinteraction',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks.recommendationsnapshot'),
        ),
        migrations.AlterField(
            model_name='recommendationinteraction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recommendationsnapshot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProductConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_score', models.IntegerField(blank=True, null=True)),
                ('max_dti', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('min_income', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='banks.bankproduct')),
            ],
        ),
        migrations.RemoveField(
            model_name='bankproduct',
            name='max_dti',
        ),
        migrations.RemoveField(
            model_name='bankproduct',
            name='min_income',
        ),
        migrations.RemoveField(
            model_name='bankproduct',
            name='min_score',
        ),
    ]
