# Generated by Django 5.0.4 on 2026-04-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0013_bankproduct_max_dti_bankproduct_min_income_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bankproduct',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='unique_key',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
