# Generated by Django 5.0.4 on 2026-04-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0014_alter_bankproduct_unique_together_bankproduct_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankproduct',
            name='unique_key',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
