# Generated by Django 5.0.4 on 2026-04-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0015_alter_bankproduct_unique_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankproduct',
            name='aggregated_key',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='is_online',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='bankproduct',
            name='product_type',
            field=models.CharField(choices=[('loan', 'Loan'), ('micro', 'Microloan'), ('auto', 'Auto Loan'), ('mortgage', 'Mortgage'), ('credit_card', 'Credit Card'), ('deposit', 'Deposit')], db_index=True, default='loan', max_length=20),
        ),
        migrations.AddIndex(
            model_name='bankproduct',
            index=models.Index(fields=['normalized_name', 'product_type'], name='banks_bankp_normali_5a1711_idx'),
        ),
        migrations.AddIndex(
            model_name='bankproduct',
            index=models.Index(fields=['aggregated_key'], name='banks_bankp_aggrega_58d694_idx'),
        ),
    ]
