# Generated by Django 5.0.4 on 2026-04-16 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0016_bankproduct_aggregated_key_bankproduct_is_online_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(db_index=True, max_length=255)),
                ('product_type', models.CharField(db_index=True, max_length=20)),
                ('min_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('best_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('offers_count', models.IntegerField(default=0)),
                ('is_online', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['best_rate'],
            },
        ),
        migrations.RemoveField(
            model_name='recommendationinteraction',
            name='product',
        ),
        migrations.RemoveField(
            model_name='recommendationinteraction',
            name='snapshot',
        ),
        migrations.RemoveField(
            model_name='recommendationinteraction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='recommendationsnapshot',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='bankproduct',
            options={'ordering': ['interest_rate']},
        ),
        migrations.RemoveField(
            model_name='bankproduct',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='bankproduct',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='bankproduct',
            name='has_rate',
        ),
        migrations.RemoveField(
            model_name='bankproduct',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='bankproduct',
            name='max_dti',
        ),
        migrations.RemoveField(
            model_name='bankproduct',
            name='min_income',
        ),
        migrations.RemoveField(
            model_name='bankproduct',
            name='min_score',
        ),
        migrations.RemoveField(
            model_name='bankproduct',
            name='source',
        ),
        migrations.AlterField(
            model_name='bank',
            name='normalized_name',
            field=models.CharField(db_index=True, default='temp', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankproduct',
            name='aggregated_key',
            field=models.CharField(db_index=True, default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankproduct',
            name='normalized_name',
            field=models.CharField(db_index=True, default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankproduct',
            name='product_type',
            field=models.CharField(choices=[('loan', 'Loan'), ('micro', 'Microloan'), ('auto', 'Auto Loan'), ('mortgage', 'Mortgage')], db_index=True, default='loan', max_length=20),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='aggregated_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='banks.aggregatedproduct'),
        ),
        migrations.DeleteModel(
            name='BankBranch',
        ),
        migrations.DeleteModel(
            name='RecommendationInteraction',
        ),
        migrations.DeleteModel(
            name='RecommendationSnapshot',
        ),
    ]
