# Generated by Django 5.0.4 on 2026-04-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0017_aggregatedproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregatedproduct',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
