# Generated by Django 5.0.4 on 2026-04-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0018_aggregatedproduct_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankproduct',
            options={'ordering': ['-has_rate', 'interest_rate']},
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='has_rate',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='max_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='min_rate',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='bankproduct',
            name='aggregated_key',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='bankproduct',
            index=models.Index(fields=['min_rate'], name='banks_bankp_min_rat_3ffbd4_idx'),
        ),
    ]
