# Generated by Django 5.0.4 on 2026-04-20 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0019_alter_bankproduct_options_bankproduct_has_rate_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bankproduct',
            name='banks_bankp_aggrega_58d694_idx',
        ),
        migrations.RemoveField(
            model_name='bankproduct',
            name='aggregated_key',
        ),
        migrations.AlterField(
            model_name='aggregatedproduct',
            name='normalized_name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='bankproduct',
            name='aggregated_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='banks.aggregatedproduct'),
        ),
        migrations.AlterField(
            model_name='bankproduct',
            name='max_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
