# Generated by Django 5.0.4 on 2026-04-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0020_remove_bankproduct_banks_bankp_aggrega_58d694_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='type',
            field=models.CharField(choices=[('bank', 'Bank'), ('fintech', 'Fintech'), ('mfo', 'Microfinance')], db_index=True, default='bank', max_length=20),
        ),
        migrations.AlterField(
            model_name='bank',
            name='short_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
