# Generated by Django 5.0.4 on 2026-04-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0021_bank_type_alter_bank_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregatedproduct',
            name='normalized_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='aggregatedproduct',
            unique_together={('normalized_name', 'product_type')},
        ),
    ]
