# Generated by Django 5.0.4 on 2026-04-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0022_alter_aggregatedproduct_normalized_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankproduct',
            options={'ordering': ['-score', '-has_rate', 'interest_rate']},
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='score',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='bankproduct',
            index=models.Index(fields=['score'], name='banks_bankp_score_0fcdb0_idx'),
        ),
    ]
