# Generated by Django 5.0.4 on 2026-04-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0023_alter_bankproduct_options_bankproduct_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankproduct',
            name='term_max',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='term_min',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='bankproduct',
            index=models.Index(fields=['term_min', 'term_max'], name='banks_bankp_term_mi_a0b5d0_idx'),
        ),
    ]
