# Generated by Django 5.0.4 on 2026-04-22 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0024_bankproduct_term_max_bankproduct_term_min_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankproduct',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='banks.bank'),
        ),
    ]
