# Generated by Django 5.0.4 on 2026-04-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0025_alter_bankproduct_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankproduct',
            name='bank_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='is_partner',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='last_parsed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
