# Generated by Django 5.0.4 on 2026-04-24 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0026_bankproduct_bank_url_bankproduct_is_partner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankproduct',
            name='fee',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='loan_type',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='real_online',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BankBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('city', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, db_index=True, null=True)),
                ('longitude', models.FloatField(blank=True, db_index=True, null=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='banks.bank')),
            ],
            options={
                'indexes': [models.Index(fields=['bank'], name='banks_bankb_bank_id_706928_idx'), models.Index(fields=['latitude', 'longitude'], name='banks_bankb_latitud_82475a_idx')],
                'unique_together': {('bank', 'address')},
            },
        ),
    ]
