# Generated by Django 5.0.4 on 2026-05-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0027_bankproduct_fee_bankproduct_loan_type_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bankbranch',
            name='banks_bankb_bank_id_706928_idx',
        ),
        migrations.RemoveIndex(
            model_name='bankbranch',
            name='banks_bankb_latitud_82475a_idx',
        ),
        migrations.RemoveIndex(
            model_name='bankproduct',
            name='banks_bankp_normali_5a1711_idx',
        ),
        migrations.RemoveIndex(
            model_name='bankproduct',
            name='banks_bankp_min_rat_3ffbd4_idx',
        ),
        migrations.RemoveIndex(
            model_name='bankproduct',
            name='banks_bankp_score_0fcdb0_idx',
        ),
        migrations.RemoveIndex(
            model_name='bankproduct',
            name='banks_bankp_term_mi_a0b5d0_idx',
        ),
        migrations.AddField(
            model_name='bank',
            name='unique_key',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='normalized_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bankproduct',
            name='product_type',
            field=models.CharField(choices=[('loan', 'Loan'), ('micro', 'Microloan'), ('auto', 'Auto Loan'), ('mortgage', 'Mortgage'), ('education', 'Education'), ('overdraft', 'Overdraft'), ('business', 'Business Loan'), ('green', 'Green Loan')], db_index=True, default='loan', max_length=20),
        ),
    ]
