# Generated by Django 5.0.4 on 2026-05-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0028_remove_bankbranch_banks_bankb_bank_id_706928_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='unique_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bankproduct',
            name='unique_key',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
