# Generated by Django 5.0.4 on 2026-05-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0029_alter_bank_unique_key_alter_bankproduct_unique_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankbranch',
            options={'ordering': ['bank__name', 'city', 'address']},
        ),
        migrations.AlterUniqueTogether(
            name='bankbranch',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bankbranch',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='bankbranch',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bankbranch',
            name='geocode_provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bankbranch',
            name='geocoded',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='bankbranch',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='bankbranch',
            name='last_parsed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankbranch',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bankbranch',
            name='normalized_address',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='bankbranch',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bankbranch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bankbranch',
            name='working_hours',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='bankbranch',
            unique_together={('bank', 'normalized_address')},
        ),
        migrations.AddIndex(
            model_name='bankbranch',
            index=models.Index(fields=['city'], name='banks_bankb_city_cf4ac3_idx'),
        ),
        migrations.AddIndex(
            model_name='bankbranch',
            index=models.Index(fields=['latitude', 'longitude'], name='banks_bankb_latitud_82475a_idx'),
        ),
        migrations.AddIndex(
            model_name='bankbranch',
            index=models.Index(fields=['bank', 'city'], name='banks_bankb_bank_id_28cda1_idx'),
        ),
        migrations.AddIndex(
            model_name='bankbranch',
            index=models.Index(fields=['is_active'], name='banks_bankb_is_acti_336646_idx'),
        ),
    ]
