# Generated by Django 5.0.4 on 2026-05-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0030_alter_bankbranch_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankproduct',
            options={'ordering': ['-score', '-real_online', '-has_rate', 'interest_rate']},
        ),
        migrations.AddField(
            model_name='bank',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='last_parsed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='license_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='parser_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='support_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='telegram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='card_system',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='card_type',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='currency',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='documents_required',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='duplicate_group',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='has_branch',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='is_premium',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='is_salary_card',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='is_virtual',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='issue_cost',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='open_methods',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='parse_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='parse_success',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='parser_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='search_vector',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='service_cost',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='source_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='source_name',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='updated_from_source',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='validity_period',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bankproduct',
            name='product_type',
            field=models.CharField(choices=[('loan', 'Loan'), ('deposit', 'Deposit'), ('card', 'Card'), ('micro', 'Microloan'), ('auto', 'Auto Loan'), ('mortgage', 'Mortgage'), ('education', 'Education'), ('overdraft', 'Overdraft'), ('business', 'Business Loan'), ('green', 'Green Loan')], db_index=True, default='loan', max_length=20),
        ),
        migrations.AddIndex(
            model_name='bankproduct',
            index=models.Index(fields=['product_type'], name='banks_bankp_product_2fdd24_idx'),
        ),
        migrations.AddIndex(
            model_name='bankproduct',
            index=models.Index(fields=['bank'], name='banks_bankp_bank_id_1a6f6a_idx'),
        ),
        migrations.AddIndex(
            model_name='bankproduct',
            index=models.Index(fields=['currency'], name='banks_bankp_currenc_106d06_idx'),
        ),
        migrations.AddIndex(
            model_name='bankproduct',
            index=models.Index(fields=['card_system'], name='banks_bankp_card_sy_83fca9_idx'),
        ),
        migrations.AddIndex(
            model_name='bankproduct',
            index=models.Index(fields=['interest_rate'], name='banks_bankp_interes_aaef62_idx'),
        ),
        migrations.AddIndex(
            model_name='bankproduct',
            index=models.Index(fields=['is_online'], name='banks_bankp_is_onli_b5c46f_idx'),
        ),
        migrations.AddIndex(
            model_name='bankproduct',
            index=models.Index(fields=['updated_from_source'], name='banks_bankp_updated_ea94bf_idx'),
        ),
    ]
