# Generated by Django 5.0.4 on 2026-05-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0031_alter_bankproduct_options_bank_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankproduct',
            name='bank_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='bankproduct',
            index=models.Index(fields=['bank_name'], name='banks_bankp_bank_na_1b6b20_idx'),
        ),
    ]
