# Generated by Django 5.0.4 on 2026-07-05 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0032_bankproduct_bank_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('featured', models.BooleanField(db_index=True, default=False)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Дополнительный приоритет банка')),
                ('min_score', models.PositiveIntegerField(default=0)),
                ('max_score', models.PositiveIntegerField(default=1000)),
                ('min_income', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('max_dti', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('show_dashboard', models.BooleanField(default=True)),
                ('show_recommendations', models.BooleanField(default=True)),
                ('show_landing', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_rule', to='banks.bank')),
            ],
            options={
                'verbose_name': 'Recommendation Rule',
                'verbose_name_plural': 'Recommendation Rules',
                'ordering': ['-featured', '-priority', 'bank__name'],
            },
        ),
    ]
