# Generated by Django 5.0.4 on 2026-07-06 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0033_recommendationrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('badge', models.CharField(choices=[('promo', '🔥 Акция'), ('top', '⭐ TOP'), ('cashback', '💰 Cashback'), ('mortgage', '🏠 Ипотека'), ('auto', '🚗 Автокредит'), ('business', '💼 Бизнес'), ('green', '🌿 Green')], default='promo', max_length=30)),
                ('bonus_score', models.PositiveIntegerField(default=10)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('show_dashboard', models.BooleanField(default=True)),
                ('show_recommendations', models.BooleanField(default=True)),
                ('show_landing', models.BooleanField(default=False)),
                ('starts_at', models.DateField(blank=True, null=True)),
                ('ends_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='banks.bank')),
            ],
            options={
                'verbose_name': 'Recommendation Campaign',
                'verbose_name_plural': 'Recommendation Campaigns',
                'ordering': ('-priority', '-bonus_score', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='RecommendationReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('reason_type', models.CharField(choices=[('score', 'Высокий скоринг'), ('income', 'Доход соответствует'), ('dti', 'Низкая долговая нагрузка'), ('employment', 'Подтвержденная занятость'), ('history', 'Хорошая кредитная история'), ('partner', 'Партнер BankAnalytics'), ('featured', 'Избранный банк'), ('campaign', 'Маркетинговая акция'), ('online', 'Онлайн оформление'), ('rate', 'Выгодная процентная ставка'), ('limit', 'Высокий кредитный лимит'), ('custom', 'Пользовательская')], db_index=True, default='custom', max_length=30)),
                ('bonus_score', models.PositiveIntegerField(default=0, help_text='Дополнительные баллы рекомендации')),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('show_dashboard', models.BooleanField(default=True)),
                ('show_recommendations', models.BooleanField(default=True)),
                ('show_landing', models.BooleanField(default=False)),
                ('starts_at', models.DateField(blank=True, null=True)),
                ('ends_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_reasons', to='banks.bank')),
            ],
            options={
                'verbose_name': 'Recommendation Reason',
                'verbose_name_plural': 'Recommendation Reasons',
                'ordering': ('-priority', '-bonus_score', 'title'),
            },
        ),
    ]
