# Generated by Django 5.0.4 on 2026-07-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0034_recommendationcampaign_recommendationreason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendationreason',
            name='ends_at',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='recommendationreason',
            name='starts_at',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='recommendationrule',
            name='valid_from',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='recommendationrule',
            name='valid_to',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='recommendationreason',
            index=models.Index(fields=['bank', 'enabled'], name='banks_recom_bank_id_e479f6_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationreason',
            index=models.Index(fields=['reason_type', 'enabled'], name='banks_recom_reason__d0ee82_idx'),
        ),
    ]
