# Generated by Django 5.0 on 2026-02-26 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='credit_reports/')),
                ('extracted_income', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('extracted_debt', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('credit_score', models.IntegerField(blank=True, null=True)),
                ('parsed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
