# Generated by Django 5.0.4 on 2026-06-28 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditreport',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='creditreport',
            name='contracts_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creditreport',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='creditreport',
            name='overdue_debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='creditreport',
            name='passport',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='creditreport',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='creditreport',
            name='risk_class',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='creditreport',
            name='score_version',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='creditreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='creditreport',
            name='credit_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='creditreport',
            name='extracted_debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='creditreport',
            name='extracted_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.CreateModel(
            name='CreditContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('contract_number', models.CharField(blank=True, max_length=255)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(default='UZS', max_length=20)),
                ('issued_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('current_debt', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('overdue_debt', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('monthly_payment', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('OVERDUE', 'Overdue'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='credit_analysis.creditreport')),
            ],
            options={
                'ordering': ['-issued_date', 'bank_name'],
            },
        ),
    ]
