# Generated by Django 5.0.4 on 2026-07-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_analysis', '0002_alter_creditreport_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditcontract',
            options={'ordering': ['-issued_date', 'bank_name'], 'verbose_name': 'Credit contract', 'verbose_name_plural': 'Credit contracts'},
        ),
        migrations.AlterModelOptions(
            name='creditreport',
            options={'ordering': ['-created_at'], 'verbose_name': 'Credit report', 'verbose_name_plural': 'Credit reports'},
        ),
        migrations.AlterField(
            model_name='creditreport',
            name='credit_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
