# Generated by Django 5.0.4 on 2026-07-05 11:55

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditscore',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='creditscore',
            name='dti_ratio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='creditscore',
            name='dti_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creditscore',
            name='employment_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creditscore',
            name='history_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creditscore',
            name='income_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creditscore',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='creditscore',
            name='monthly_obligations',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='creditscore',
            name='net_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='creditscore',
            name='profile_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creditscore',
            name='recommended_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='creditscore',
            name='approval_probability',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='creditscore',
            name='profile_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='creditscore',
            name='risk_category',
            field=models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('REJECT', 'Reject')], default='HIGH', max_length=10),
        ),
        migrations.AlterField(
            model_name='creditscore',
            name='score',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AddIndex(
            model_name='creditscore',
            index=models.Index(fields=['user', '-created_at'], name='scoring_cre_user_id_ed92e7_idx'),
        ),
        migrations.AddIndex(
            model_name='creditscore',
            index=models.Index(fields=['score'], name='scoring_cre_score_cf44f7_idx'),
        ),
    ]
