# Generated by Django 5.0.4 on 2026-03-31 08:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_financialprofile_is_profile_completed_employment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='credit_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='expenses',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='income',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='job_type',
            field=models.CharField(choices=[('employee', 'Employee'), ('self', 'Self-employed'), ('business', 'Business')], default='employee', max_length=20),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='passport',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
