# Generated by Django 5.0.4 on 2026-06-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_financialprofile_birth_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialprofile',
            old_name='experience',
            new_name='work_experience_months',
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='company_inn',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='department',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='employment_document',
            field=models.FileField(blank=True, null=True, upload_to='employment/'),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='employment_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='employment_pinfl',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='employment_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='employment_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='is_current_employee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='position',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
